export default {
	YA_COUNTER_NAME: '',
	LIVE_HOST: "",
	API_HOST: "",
	API_DEFAULT_ACTION: '/api/Form',

	STORAGE_AUTH_TOKEN: "auth",
	STORAGE_PROP_ORDER_HASH: "orderHash",
	STORAGE_PROP_USER_ID: "userId",

	ERROR_CODE_FORBIDDEN: 403,
	API_EXCEPTION_NOT_FOUND: 'NOT_FOUND',
	API_EXCEPTION_FORBIDDEN: 'FORBIDDEN',
	API_EXCEPTION_RESTART: 'RESTART',
	API_EXCEPTION_EMAIL_EXISTS: 'EMAIL_EXISTS',
	API_EXCEPTION_PHONE_EXISTS: 'PHONE_EXISTS',
	API_EXCEPTION_SUSPENDED: 'SUSPENDED',

	//in _variables.scss, config.js and plugins/vuetify.js
	WIDTH_SM: 600,
	WIDTH_MD: 1024,
	WIDTH_LG: 1440,
	WIDTH_XL: 1920,

	HEADER_MD: 1280,

	LAYOUT_MARGIN_XS:32,

	LINK_RU: "https://memostory.ru/",
	LINK_ENG: "https://memo-story.com/",
}
